### ISSUE TITLE
Some suggestions to list of TODOs

### ISSUE THREAD

**Issue by lervag** [ii14/neopm.nvim#2]
I'm a happy user of vim-plug, and I can't really see any benefit of the vim package feature. Thus packer is not really interesting to me. However, I have noticed that vim-plug may be slower than necessary, and it would also be of interest with a similar plugin that allows lua based configuration. Thus, I am glad to see this project!

Two things I miss:

* Slightly more informative README - write out what this plugin is and what it isn't. Make it clear how it stands out from other similar plugins.
* Documentation: The features should be documented in `doc/neopm.txt` and be available in `:help neopm`.

**Comment by ii14** [comment]
Sure, all of this is planned.

To give some answers right now, this is indeed inspired by vim-plug, but focused primarily on startup speed and not so much on the minimalism aspect of vim-plug. Some features are still missing to even have feature parity with vim-plug, but the idea I had in mind is just having a bigger control over plugins, like for example the already implemented patching and everything else that is mentioned on the TODO list.

The full documentation will happen, but it requires changing the directory structure, so it's going to be a breaking change.

**Comment by lervag** [comment]
Glad to hear it! I will be watching the project and will migrate from vim-plug when I have the time. If I have any issues I will let you know.
